### ISSUE TITLE
Where can I download the dataset?

### ISSUE THREAD

**Issue by Reagan1311** [spthermo/STCAE#1]
Hi, thanks for the great work. Just wanna know where can I get the dataset? I have requested access to the dataset in your official website, but got no reply afterward.

**Comment by spthermo** [comment]
Hi, thanks for your interest in our work. Due to my relocation (changing institutes) and the under-maintenance during the pandemic, the intermediate server is not active currently. Will try to regain access at some point, but it will not be soon. I am really sorry for that but the size of the dataset (3TB) does not allow for much flexibility!

**Comment by Reagan1311** [comment]
Understood, thanks for your reply!
